//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvDeneme.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginInfo
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Boþ býrakýlmaz")]
        [EmailAddress(ErrorMessage = "Geçerli bir e-mail giriniz")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Boþ býrakýlmaz")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
